export const boardThemes = {
  classic: {
    id: 'classic',
    name: 'Classic',
    description: 'Traditional Sudoku board design',
    colors: {
      background: '#ffffff',
      grid: '#000000',
      boxBorder: '#000000',
      cellBorder: '#cccccc',
      initialNumber: '#000000',
      userNumber: '#0066cc',
      highlightBackground: '#f0f0f0',
      selectedBackground: '#e3f2fd',
      errorBackground: '#ffebee',
      noteText: '#666666',
    },
    borderWidths: {
      box: 2,
      cell: 1,
    },
  },
  modern: {
    id: 'modern',
    name: 'Modern',
    description: 'Clean and minimalist design',
    colors: {
      background: '#fafafa',
      grid: '#424242',
      boxBorder: '#424242',
      cellBorder: '#e0e0e0',
      initialNumber: '#212121',
      userNumber: '#1976d2',
      highlightBackground: '#f5f5f5',
      selectedBackground: '#bbdefb',
      errorBackground: '#ffcdd2',
      noteText: '#757575',
    },
    borderWidths: {
      box: 1.5,
      cell: 0.5,
    },
  },
  dark: {
    id: 'dark',
    name: 'Dark Mode',
    description: 'Easy on the eyes',
    colors: {
      background: '#121212',
      grid: '#ffffff',
      boxBorder: '#ffffff',
      cellBorder: '#424242',
      initialNumber: '#ffffff',
      userNumber: '#64b5f6',
      highlightBackground: '#1e1e1e',
      selectedBackground: '#0d47a1',
      errorBackground: '#b71c1c',
      noteText: '#9e9e9e',
    },
    borderWidths: {
      box: 1.5,
      cell: 0.5,
    },
  },
  nature: {
    id: 'nature',
    name: 'Nature',
    description: 'Soothing earth tones',
    colors: {
      background: '#f1f8e9',
      grid: '#33691e',
      boxBorder: '#33691e',
      cellBorder: '#c5e1a5',
      initialNumber: '#1b5e20',
      userNumber: '#2e7d32',
      highlightBackground: '#dcedc8',
      selectedBackground: '#c5e1a5',
      errorBackground: '#ffccbc',
      noteText: '#558b2f',
    },
    borderWidths: {
      box: 2,
      cell: 1,
    },
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean',
    description: 'Calming blue tones',
    colors: {
      background: '#e1f5fe',
      grid: '#01579b',
      boxBorder: '#01579b',
      cellBorder: '#81d4fa',
      initialNumber: '#01579b',
      userNumber: '#0288d1',
      highlightBackground: '#b3e5fc',
      selectedBackground: '#81d4fa',
      errorBackground: '#ffcdd2',
      noteText: '#0277bd',
    },
    borderWidths: {
      box: 2,
      cell: 1,
    },
  },
};
